-- ADICIONAR PRIMARY KEY E AUTO INCERMENT

ALTER TABLE `crianca` ADD PRIMARY KEY(`id`);

ALTER TABLE `crianca` MODIFY `id` INTEGER NOT NULL AUTO_INCREMENT;

ALTER TABLE `crianca` AUTO_INCREMENT = 1;

